### ISSUE TITLE
TG does not revert changes made to structured data

### ISSUE THREAD

**Issue by jdx-gh** [Xi-Plus/twinkle-global#31]
Example: https://commons.wikimedia.org/w/index.php?title=File:Emblem_of_Brunei.svg&diff=568112257&oldid=568110158

**Comment by Xi-Plus** [comment]
mcrundo is not supported by API.

**Comment by jdx-gh** [comment]
However [Navigation popups](https://en.wikipedia.org/wiki/Wikipedia:Tools/Navigation_popups) somehow are able to undo such changes. This bug gives people who use TH false impression that they have undone a vandalism while actually they have not.

**Comment by Xi-Plus** [comment]
@jdx-gh How to revert it by popups? Tell me the steps.

**Comment by Xi-Plus** [comment]
Put cursor on diff link, then click "action" > "revert". Right?

**Comment by jdx-gh** [comment]
> Put cursor on diff link, then click "actions" > "revert". Right?

Right!

**Comment by Xi-Plus** [comment]
I use popups to revert a structured data change on commons. Then I got:
> You cannot edit the wikitext on this revision of the page, as there have been changes to the data on the page since this revision that are not wikitext-based. To restore this revision click here.

**Comment by Xi-Plus** [comment]
Popup takes me to https://commons.wikimedia.org/w/index.php?title=File:JPG_Test.jpg&action=edit&oldid=622323765 .
It's wrong. Correct URL is https://commons.wikimedia.org/w/index.php?title=File:JPG_Test.jpg&action=mcrrestore&restore=622323765

**Comment by Xi-Plus** [comment]
I used same feature to revert wikitext edits. I found popups use regular editor to revert the edit instead of API.
