### ISSUE TITLE
Wrap deletion template on Translation namespace

### ISSUE THREAD

**Issue by libkoi** [Xi-Plus/twinkle-global#41]
As the delete template will also be shown on the main page, I suggest adding a feature to wrap the deletion tag with `<noinclude>`. This feature should be enabled on "Translation" namespace, and optional on other namespaces.

FYI: [talkpage discussion](https://commons.wikimedia.org/w/index.php?oldid=613478918#Your_account_has_been_blocked), [relevant task on Phabricator](https://phabricator.wikimedia.org/T154183).

**Comment by Xi-Plus** [comment]
@libkoi noinclude is not working for Translation namespace.

**Comment by Xi-Plus** [comment]
I added the feature. But not enabled on Translation namespace by default.
